In [1]:
import cv2
import torch
import matplotlib.pyplot as plt

## Download the MiDaS

In [ ]:
midas = torch.hub.load('intel-isl/MiDaS', 'MiDaS_small')
midas.eval()

## Transformational Pipeline


In [4]:
transforms = torch.hub.load('intel-isl/MiDaS', 'transforms')
transform = transforms.small_transform

Using cache found in C:\Users\admin/.cache\torch\hub\intel-isl_MiDaS_master


In [7]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
  ret, frame = cap.read()

  img = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
  imgbatch = transform(img)

  with torch.no_grad():
    prediction = midas(imgbatch)
    prediction = torch.nn.functional.interpolate(
      prediction.unsqueeze(1),
      size = img.shape[:2],
      mode = 'bicubic',
      align_corners = False,
    ).squeeze()

    output = prediction.cpu().numpy()
    print(output)

  cv2.imshow('Frame', frame)
  if cv2.waitKey(10) & 0xFF == ord('q'):
    cap.release()
    cv2.destroyAllWindows()

[[263.10318 262.576   261.58612 ... 283.77917 262.5832  252.427  ]
 [263.07367 262.34183 260.89996 ... 290.04767 271.3711  262.48657]
 [263.436   262.15912 259.51257 ... 303.4452  290.04477 283.82996]
 ...
 [444.24152 444.86304 446.47464 ... 886.8222  877.2268  874.01965]
 [440.61978 441.22726 442.5277  ... 888.63324 878.7686  875.61285]
 [439.131   439.7737  441.03748 ... 889.7356  879.58856 876.38574]]
[[348.51367 347.65027 345.92978 ... 350.8049  324.9092  312.48166]
 [348.1393  347.08932 344.9645  ... 358.1539  335.3216  324.44183]
 [347.86838 346.29388 343.02856 ... 373.87503 357.435   349.79514]
 ...
 [413.85245 414.59238 416.47626 ... 801.1011  794.6417  792.6937 ]
 [410.1403  410.83258 412.3101  ... 799.53235 791.4692  788.8889 ]
 [408.52823 409.2361  410.61856 ... 799.1028  790.1668  787.2339 ]]
[[436.93192 435.85608 433.72363 ... 399.95575 370.31317 356.07654]
 [436.35168 435.0428  432.42584 ... 408.7371  382.66364 370.22626]
 [435.67313 433.72452 429.76422 ... 427.51843 408.